INSERT INTO foods (name, name_alt, calories, protein, carbs, fat, serving, brand, category, source) VALUES
('Kauai PB Bomb Large', ARRAY['kauai peanut butter bomb large','pbb large'], 764, 22, 98, 32, 'Large 500ml', 'Kauai', 'restaurant', 'Manual'),
('Kauai PB Bomb Small', ARRAY['kauai peanut butter bomb small','pbb small'], 467, 14, 60, 20, 'Small 350ml', 'Kauai', 'restaurant', 'Manual'),
('Kauai Green Machine Large', ARRAY['kauai green machine large'], 380, 8, 82, 2, 'Large 500ml', 'Kauai', 'restaurant', 'Manual'),
('Kauai Green Machine Small', ARRAY['kauai green machine small'], 266, 6, 57, 1, 'Small 350ml', 'Kauai', 'restaurant', 'Manual'),
('Kauai Triple C Large', ARRAY['kauai triple c large'], 510, 4, 122, 1, 'Large 500ml', 'Kauai', 'restaurant', 'Manual'),
('Kauai Triple C Small', ARRAY['kauai triple c small'], 357, 3, 85, 1, 'Small 350ml', 'Kauai', 'restaurant', 'Manual'),
('Nandos Quarter Chicken Branded', ARRAY['nandos quarter chicken branded'], 429, 45, 0, 27, 'skin on', 'Nandos', 'restaurant', 'Manual'),
('Nandos Half Chicken Branded', ARRAY['nandos half chicken branded'], 858, 90, 0, 54, '1 serving', 'Nandos', 'restaurant', 'Manual'),
('Nandos Full Chicken', ARRAY['nandos full chicken','whole chicken'], 1716, 180, 0, 108, '1 serving', 'Nandos', 'restaurant', 'Manual'),
('Nandos Pita', ARRAY['nandos pita','nandos chicken pita'], 420, 32, 45, 12, '1 serving', 'Nandos', 'restaurant', 'Manual'),
('Nandos Wrap', ARRAY['nandos wrap','nandos chicken wrap'], 480, 28, 48, 18, '1 serving', 'Nandos', 'restaurant', 'Manual'),
('Nandos Fino Burger', ARRAY['nandos fino burger','fino burger'], 580, 35, 52, 25, '1 serving', 'Nandos', 'restaurant', 'Manual'),
('Nandos Supergrain Burger', ARRAY['nandos supergrain'], 520, 28, 58, 18, '1 serving', 'Nandos', 'restaurant', 'Manual'),
('Nandos Peri Chips', ARRAY['nandos peri chips','nandos chips'], 430, 6, 58, 20, 'regular', 'Nandos', 'restaurant', 'Manual'),
('Nandos Coleslaw', ARRAY['nandos coleslaw','nandos slaw'], 140, 2, 12, 10, 'regular', 'Nandos', 'restaurant', 'Manual'),
('Nandos Corn', ARRAY['nandos corn','nandos mielie'], 120, 4, 25, 2, '1 serving', 'Nandos', 'restaurant', 'Manual'),
('Nandos Rice', ARRAY['nandos rice','nandos spicy rice'], 350, 7, 68, 6, 'regular', 'Nandos', 'restaurant', 'Manual'),
('Nandos Garlic Bread', ARRAY['nandos garlic bread'], 280, 8, 38, 12, '1 serving', 'Nandos', 'restaurant', 'Manual'),
('Nandos Wings 5pc', ARRAY['nandos wings 5','5 wings nandos'], 340, 35, 0, 22, '5 pieces', 'Nandos', 'restaurant', 'Manual'),
('Nandos Wings 10pc', ARRAY['nandos wings 10','10 wings nandos'], 680, 70, 0, 44, '10 pieces', 'Nandos', 'restaurant', 'Manual'),
('Nandos Espetada', ARRAY['nandos espetada'], 520, 55, 8, 30, '1 serving', 'Nandos', 'restaurant', 'Manual'),
('Steers Regular Burger', ARRAY['steers burger','steers regular'], 520, 28, 45, 25, '1 serving', 'Steers', 'restaurant', 'Manual'),
('Steers Cheese Burger', ARRAY['steers cheeseburger'], 580, 32, 46, 30, '1 serving', 'Steers', 'restaurant', 'Manual'),
('Steers King Steer', ARRAY['steers king steer burger'], 720, 42, 48, 38, '1 serving', 'Steers', 'restaurant', 'Manual'),
('Steers Bacon Burger', ARRAY['steers bacon burger'], 650, 35, 47, 35, '1 serving', 'Steers', 'restaurant', 'Manual'),
('Steers Chicken Burger', ARRAY['steers chicken'], 540, 30, 50, 22, '1 serving', 'Steers', 'restaurant', 'Manual'),
('Steers Onion Rings', ARRAY['steers rings'], 330, 4, 42, 16, 'regular', 'Steers', 'restaurant', 'Manual'),
('Steers Chips', ARRAY['steers chips','steers fries'], 380, 5, 52, 18, 'regular', 'Steers', 'restaurant', 'Manual'),
('Steers Ribs Full', ARRAY['steers ribs full rack'], 1200, 85, 45, 75, '1 serving', 'Steers', 'restaurant', 'Manual'),
('Steers Ribs Half', ARRAY['steers ribs half rack'], 600, 42, 22, 38, '1 serving', 'Steers', 'restaurant', 'Manual'),
('Steers Milkshake', ARRAY['steers shake'], 450, 12, 68, 15, 'regular', 'Steers', 'restaurant', 'Manual'),
('KFC Streetwise 2', ARRAY['kfc sw2'], 680, 48, 58, 28, '1 serving', 'KFC', 'restaurant', 'Manual'),
('KFC Streetwise 5', ARRAY['kfc sw5'], 1400, 95, 120, 55, '1 serving', 'KFC', 'restaurant', 'Manual'),
('KFC Zinger', ARRAY['kfc zinger burger'], 520, 25, 54, 22, '1 serving', 'KFC', 'restaurant', 'Manual'),
('KFC Crunch', ARRAY['kfc crunch burger'], 480, 22, 50, 20, '1 serving', 'KFC', 'restaurant', 'Manual'),
('KFC Dunked Wings', ARRAY['kfc wings'], 450, 35, 20, 25, '6 pieces', 'KFC', 'restaurant', 'Manual'),
('KFC Chips', ARRAY['kfc chips','kfc fries'], 360, 4, 48, 18, 'regular', 'KFC', 'restaurant', 'Manual'),
('KFC Coleslaw', ARRAY['kfc slaw'], 150, 2, 15, 9, 'regular', 'KFC', 'restaurant', 'Manual'),
('KFC Dunked Burger', ARRAY['kfc dunked'], 580, 28, 52, 28, '1 serving', 'KFC', 'restaurant', 'Manual'),
('McDonalds Big Mac', ARRAY['big mac','mcdonalds big mac'], 540, 25, 45, 28, '1 serving', 'McDonalds', 'restaurant', 'Manual'),
('McDonalds Quarter Pounder', ARRAY['quarter pounder'], 520, 30, 42, 26, '1 serving', 'McDonalds', 'restaurant', 'Manual'),
('McDonalds Chicken Legend', ARRAY['chicken legend'], 490, 24, 48, 22, '1 serving', 'McDonalds', 'restaurant', 'Manual'),
('McDonalds McChicken', ARRAY['mcchicken'], 400, 14, 39, 21, '1 serving', 'McDonalds', 'restaurant', 'Manual'),
('McDonalds Fries', ARRAY['mcdonalds fries','mcdonalds chips'], 340, 4, 45, 16, 'medium', 'McDonalds', 'restaurant', 'Manual'),
('McDonalds McFlurry', ARRAY['mcflurry'], 480, 12, 70, 16, 'regular', 'McDonalds', 'restaurant', 'Manual'),
('McDonalds Cheeseburger', ARRAY['mcdonalds cheese burger'], 300, 15, 33, 12, '1 serving', 'McDonalds', 'restaurant', 'Manual'),
('Woolworths Protein Shake', ARRAY['woolies protein shake','ww protein'], 220, 20, 25, 4, '1 serving', 'Woolworths', 'restaurant', 'Manual'),
('Woolworths Smoothie', ARRAY['woolies smoothie','ww smoothie'], 280, 6, 58, 2, '1 serving', 'Woolworths', 'restaurant', 'Manual'),
('Woolworths Wrap', ARRAY['woolies wrap','ww wrap'], 380, 18, 42, 14, '1 serving', 'Woolworths', 'restaurant', 'Manual'),
('Woolworths Salad', ARRAY['woolies salad','ww salad'], 250, 12, 30, 8, '1 serving', 'Woolworths', 'restaurant', 'Manual'),
('Woolworths Sandwich', ARRAY['woolies sandwich','ww sandwich'], 320, 14, 38, 12, '1 serving', 'Woolworths', 'restaurant', 'Manual'),
('Woolworths Fruit Pot', ARRAY['woolies fruit','ww fruit'], 120, 2, 28, 0, '1 serving', 'Woolworths', 'restaurant', 'Manual'),
('Woolworths Yoghurt', ARRAY['woolies yoghurt','ww yoghurt'], 160, 8, 24, 3, '1 serving', 'Woolworths', 'restaurant', 'Manual'),
('Woolworths Muesli Bar', ARRAY['woolies muesli','ww muesli'], 180, 4, 28, 6, '1 serving', 'Woolworths', 'restaurant', 'Manual'),
('Woolworths Protein Bar', ARRAY['woolies protein bar','ww protein bar'], 220, 18, 22, 7, '1 serving', 'Woolworths', 'restaurant', 'Manual'),
('Woolworths Hummus', ARRAY['woolies hummus','ww hummus'], 180, 6, 18, 9, '1 serving', 'Woolworths', 'restaurant', 'Manual'),
('Woolworths Iced Coffee', ARRAY['woolies iced coffee'], 200, 8, 28, 6, '1 serving', 'Woolworths', 'restaurant', 'Manual'),
('Woolworths Croissant', ARRAY['woolies croissant'], 280, 6, 32, 14, '1 serving', 'Woolworths', 'restaurant', 'Manual'),
('Woolworths Muffin', ARRAY['woolies muffin','ww muffin'], 380, 5, 52, 16, '1 serving', 'Woolworths', 'restaurant', 'Manual'),
('Woolworths Sushi', ARRAY['woolies sushi','ww sushi'], 340, 12, 58, 6, 'pack', 'Woolworths', 'restaurant', 'Manual'),
('Woolworths Chicken Strips', ARRAY['woolies chicken strips'], 320, 28, 22, 12, '1 serving', 'Woolworths', 'restaurant', 'Manual'),
('Spur Burger', ARRAY['spur burger and chips'], 820, 38, 72, 38, '1 serving', 'Spur', 'restaurant', 'Manual'),
('Spur Ribs', ARRAY['spur ribs and chips'], 1100, 75, 68, 58, 'full rack', 'Spur', 'restaurant', 'Manual'),
('Spur Steak', ARRAY['spur steak and chips'], 680, 52, 45, 28, '200g', 'Spur', 'restaurant', 'Manual'),
('Spur Schnitzel', ARRAY['spur chicken schnitzel'], 750, 48, 58, 32, '1 serving', 'Spur', 'restaurant', 'Manual'),
('Spur Wings', ARRAY['spur wings and chips'], 720, 55, 52, 32, '1 serving', 'Spur', 'restaurant', 'Manual'),
('Spur Salad', ARRAY['spur garden salad'], 280, 8, 24, 14, '1 serving', 'Spur', 'restaurant', 'Manual'),
('Spur Onion Rings', ARRAY['spur rings'], 350, 4, 44, 18, '1 serving', 'Spur', 'restaurant', 'Manual'),
('Ocean Basket Hake', ARRAY['ocean basket hake and chips'], 620, 42, 52, 24, '1 serving', 'Ocean Basket', 'restaurant', 'Manual'),
('Ocean Basket Calamari', ARRAY['ocean basket calamari'], 480, 32, 38, 20, '1 serving', 'Ocean Basket', 'restaurant', 'Manual'),
('Ocean Basket Prawns', ARRAY['ocean basket prawns'], 380, 28, 18, 18, '6 prawns', 'Ocean Basket', 'restaurant', 'Manual'),
('Ocean Basket Platter', ARRAY['ocean basket fish platter'], 980, 68, 72, 42, '1 serving', 'Ocean Basket', 'restaurant', 'Manual'),
('Ocean Basket Pasta', ARRAY['ocean basket seafood pasta'], 720, 35, 78, 28, '1 serving', 'Ocean Basket', 'restaurant', 'Manual'),
('Wimpy Breakfast', ARRAY['wimpy full breakfast'], 680, 32, 58, 32, 'full breakfast', 'Wimpy', 'restaurant', 'Manual'),
('Wimpy Burger', ARRAY['wimpy burger and chips'], 750, 35, 68, 35, '1 serving', 'Wimpy', 'restaurant', 'Manual'),
('Wimpy Coffee', ARRAY['wimpy coffee'], 120, 6, 12, 5, '1 serving', 'Wimpy', 'restaurant', 'Manual'),
('Wimpy All Day', ARRAY['wimpy all day breakfast'], 820, 38, 72, 42, '1 serving', 'Wimpy', 'restaurant', 'Manual'),
('Wimpy Shake', ARRAY['wimpy milkshake'], 450, 12, 68, 15, '1 serving', 'Wimpy', 'restaurant', 'Manual')
ON CONFLICT (name) DO NOTHING;
